load("@io_bazel_rules_go//go:def.bzl", "go_binary")

go_binary(
    name = "trpc",
    srcs = [
        "trpc.go",
        "strings.go",
        "size.go"
    ],
    visibility = ["//visibility:public"],
)