load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "mrpc",
    srcs = [
        "math_mrpc.go",
        "serialization.go"
    ],
    importpath = "mrpc",
    visibility = ["//visibility:public"],
)